name: Update Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  UpdateData:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: merge web
        run: |
          git switch gh-page
          git merge main

      - name: push
        run: |
          git push
