name: Update Course Data

on:
  push:
    branches:
      - main
    paths:
      - 'crawler/**'
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1-5'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  UpdateData:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: pull data
        run: |
          f=`mktemp -d`
          python3 crawler/updateData.py 1
          mv data/*.json $f
          git checkout gh-page
          mv $f/*.json data/

      - name: commit
        run: |
          git status
          git add data/
          git commit -m "Update data ($(TZ=Asia/Taipei date -Iseconds))" || true

      - name: update list
        run: |
          ls data | jq -sRc 'split("\n")[:-1]' | tee data.json
          git add data.json
          git commit -m "Update data.json" || true

      - name: push
        run: |
          git push
