name: Update Course Data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0,8,16 * * *'

jobs:
  UpdateData:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: pull data
        run: |
          f=`mktemp -d`
          python3 updateData.py 111 2 1
          mv *.json $f
          git checkout gh-page
          mv $f/* .

      - name: commit and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git status
          git add 1112-data.json
          git commit -m "Update data"
          git push
