name: Update Web

on:
  push:
    branches:
      - web
  workflow_dispatch:

jobs:
  UpdateWeb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: merge web
        run: |
          f="$(ls)"
          git switch gh-page
          git checkout web $f

      - name: commit and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update web ($(git rev-parse web))" || true
          git push
