name: Update Web

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-web.yml
      - 'web/**'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  UpdateWeb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: setup git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: merge web
        run: |
          git fetch origin gh-page --depth 1
          git switch gh-page
          git checkout main -- web
          shopt -s dotglob
          mv web/* .
          git add .

      - name: commit and push
        run: |
          git commit -m "Update web ($(git rev-parse main))" || true
          git push
